### ISSUE TITLE
404

### ISSUE THREAD

**Issue by b0nb0n** [devinsays/laravel-react-bootstrap#1]
Hi,

I try to clone your project on my debian server. The components displayed correctly but when I want to login/register, I've 404 error in console logs.

api/v1/auth/login 404 (Not Found)

Do you have an idea ?

Best regards.

**Comment by b0nb0n** [comment]
NB:

When I try to add a test web route in web.php:

`Route::get('foo', function () {
    return 'Hello World';
});`

I can't access to the route and I've a 404 error. I don't know if that can help you.

Thanks a lot for your help.

Best regards.

**Comment by devinsays** [comment]
Hi. I tested this locally, and /foo returns the right route for me. Do you have it set up like this in web.php?

```
Route::get('foo', function () { return 'Hello World'; });

// Named route required for SendsPasswordResetEmails.
Route::get('reset-password', function() {
    return view('index');
})->name('password.reset');

// Catches all other web routes.
Route::get('{slug}', function () {
    return view('index');
})->where('slug', '^(?!api).*$');
```

`api/v1/auth/login` only accepts POST requests. Check your logs to see if a GET request was done by mistake.

**Comment by b0nb0n** [comment]
Hi,

Yes, this is exactly I've in my web.php. And I get 404 error when I try to access to xxx.io/foo.
When I try to paste theses routes in my other laravel project, everything work perfectly....
I've no idea to solve the problem

**Comment by devinsays** [comment]
I am not sure how move forward with this issue. Were you able to resolve it?
